server:
  port: 8081
spring:
  data:
    mongodb:
      uri: ENC(ql1Y4Gac/mFIY1I7Ke+5k71perGneFmRLt1owktyeSXrwKOfdavihS+ArYlcm4bgvAU05HkND5Hg3iBAZdpdRzx0/fHrQMm+mm+pMWw1jhhtKB8LSksWEkyw10lHk4iu5t1l72PXN3qZF6TmjBzPxrHWO416V8mggD8Dl1z5wvUFr727Kp3bmNpoQ9DGTuYU)
okta:
  oauth2:
    issuer: ENC(T/XhKnn9bFxoiJJYTB02gCnMhrhSPTDHDjbEfBDK9m6ncmGip4ks38avqKKHC+jZQYbJUFOV6Qs=)
    client-id: ENC(VxEkU7M95zmA+m6duJvmeYz890jJSnUzQ2/b6x3GD1w=)
    client-audience: api://default
    groupsClaim: groups
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
